### ISSUE TITLE
期末第二次分組 組員招募 使用C語言 題目OpenSync

### ISSUE THREAD

**Issue by Neol-d2022** [cccnqu/se106a_resume#11]
- 如題，期末分組組員招募。
  - PM在組員名單確定後另外決定。
  - 期末專案主要語言是C語言。
  - 期末專案題目暫定是OpenSync。

- 招募條件；
  - 熟悉C語言者佳。
  - 團隊合作能力優異者佳。
  - 主動積極者佳。
  - 溝通能力優異者佳。
  - 人數不限。

- 本文將隨時間更新。
- 有關OpenSync的功能及需求請參考[這裡](https://hackmd.io/s/SyFbyYYAb)
- 請有意應徵者在下方留言。
- 疑問、建議、或者有疏漏的地方，也歡迎在下方留言補充。
- 組員名單確認後會關閉這個issue。

- 發文者 資工四 黃政哲 110310522

**Comment by joe5343281** [comment]
JOIN！
這根本就是專題 wwwwww

**Comment by Neol-d2022** [comment]
@joe5343281 收。記憶體管理工程可以先動工。
[專案網址](https://github.com/Neol-d2022/OpenSync-se106a)
另可針對系統分析的部分內容作調整。
[系統分析](https://hackmd.io/CwNmFMEYA5wdgLQFYQGZwOEgJkhBDAIzkgVSQDM4KZwRs4AmIA==?view)

**Comment by Neol-d2022** [comment]
@joe5343281  參考資料
- [Socket 用法](http://pubs.opengroup.org/onlinepubs/009695399/functions/socket.html)
- [Socket 相關結構](http://pubs.opengroup.org/onlinepubs/000095399/basedefs/netinet/in.h.html)
- [Pthread 參考資料](http://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread.h.html)

**Comment by Neol-d2022** [comment]
組員名單

- 黃政哲
- 曾浚宥
- 魏礼謙
